# src/Acme/BConway/Resources/config/doctrine/User.orm.yml
Acme\BConway\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO