BConway\WebsiteBundle\Entity\PrivateNote:
    type: entity
    table: private_notes
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        noteText:
            type: text
            column: note_text
        noteTime:
            type: datetime
            nullable: true
            column: note_time
        createdBy:
            type: integer
            column: created_by
    manyToOne:
        job:
            targetEntity: \BConway\WebsiteBundle\Entity\Job
            inversedBy: private_notes
            joinColumn:
                name: job_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setNoteTime ]
        preUpdate: [ setNoteTime ]
