BConway\WebsiteBundle\Entity\StatusEntry:
    type: entity
    table: status_entries
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        entryTime:
            type: datetime
            nullable: true
            column: entry_time
        entryType:
            type: integer
            nullable: true
            column: entry_type
        entryNotes:
            type: text
            column: entry_notes
        createdBy:
            type: integer
            column: created_by
    manyToOne:
        job:
            targetEntity: \BConway\WebsiteBundle\Entity\Job
            inversedBy: status_entries
            joinColumn:
                name: job_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setEntryTime ]
        preUpdate: [ setEntryTime ]
